site_name: NetDEM
repo_url: https://github.com/net-dem/netdem_docs
site_url: https://net-dem.github.io/netdem_docs/
edit_uri: edit/main/docs/

theme:
  name: sandstone
  navigation_depth: 4
  # nav_style: light
  custom_dir: theme_mfem/
  features:
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Examples:
    - Random packing: examples/random_packing.md
    - Triaxial compression: examples/triaxial_compression.md
    - Angle of repose: examples/angle_of_repose.md
    - Granular mixing: examples/granular_mixing.md
  - Documentation: 
    - Installation: documentation/installation.md
    - User manual: documentation/usage.md  
    - Developer manual: documentation/developer_manual.md
    - DEM manual: documentation/dem_manual.md
    - Code manual: documentation/code_manual.md
    - Code doxygen: doxygen/html/index.html
  - Download: download/index.md
  - Gallery: examples/gallery.md
  - About:
    - Acknowledgements: about/acknowledgement.md  
    - Help: about/bugs_&_feature_requests.md
    - Publications: about/publications.md

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - extra
  - fenced_code  
  - footnotes

plugins:
  - search
  - mkdocs-video:
      mark: "video-marker"
      css_style:
        width: "50vw"
        height: "57vh"

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

