site_name: NetDEM documentation
theme:
  name: readthedocs
  custom: custom_theme/
markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  # - bibtex:
  #     bib_file: refs.bib
  #     bib_dir: docs/
  #     cite_style: pandoc
extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML