site_name: NetDEM
theme:
  name: sandstone
  navigation_depth: 3
  nav_style: light

nav:
  - Home: index.md
  - Examples:
    - Random packing: examples/random_packing.md
  - Documentation: 
    - Installation: documentation/installation.md
    - Usage: documentation/usage.md  
    - DEM basics: documentation/dem_basics.md
    - MPI algorithm: documentation/mpi_algorithm.md
    - Code framework: documentation/code_framework.md
    - Coding styles: documentation/coding_styles.md
    - Code doxygen: doxygen/html/index.html
  - About:
    - Bugs & feature request: about/bugs_&_feature_requests.md
    - Copyright: about/copyright_and_license.md
    - How to cite: about/how_to_cite.md
    - Acknowledgement: about/acknowledgement.md  

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - extra
  - fenced_code  
  - footnotes

extra:
  include_next_prev: false  

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML