site_name: NetDEM
repo_url: https://github.com/net-dem/netdem_docs
edit_uri: edit/main/docs/

theme:
  name: sandstone
  navigation_depth: 4
  # nav_style: light
  custom_dir: theme_mfem/
  features:
    - search.suggest

nav:
  - Home: index.md
  - Examples:
    - Random packing: examples/random_packing.md
    - Triaxial compression: examples/triaxial_compression.md
    - Direct shear: examples/direct_shear.md
    - Angle of repose: examples/angle_of_repose.md
    - Works based on NetDEM: examples/works_based_on_netdem.md
  - Documentation: 
    - Installation: documentation/installation.md
    - User manual: documentation/usage.md  
    - Developer manual: documentation/developer_manual.md
    - DEM introduction: documentation/dem_manual.md
    - Coding framework: documentation/code_manual.md
    - Code doxygen: doxygen/html/index.html
  - Download: download/index.md
  - Gallery: examples/gallery.md
  - About:
    - Acknowledgement: about/acknowledgement.md  
    - Help: about/bugs_&_feature_requests.md

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - extra
  - fenced_code  
  - footnotes

plugins:
  - search

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML