site_name: NetDEM documentation
theme:
  name: readthedocs
  custom: custom_theme/
nav:
  - Home: 'index.md'
  - 'User manual': 
    - 1. Installation: 'user_manual/installation.md'
    - 2. Usage: 'user_manual/usage.md'
    - 3. Bugs & feature requests: 'user_manual/bugs_feature_requests.md'
    - 4. Copyright and license: 'user_manual/copyright_and_license.md'
  - 'Validation & examples':
    - 1. Random packing: 'validation_examples/random_packing.md'
  - 'Technical manual': 
    - 1. DEM basics: 'technical_manual/dem_basics.md'
  - 'Developer manual': 
    - 1. Code framework: 'developer_manual/code_framework_cn.md'
    - 2. Coding styles: 'developer_manual/coding_styles.md'
plugins: []