site_name: NetDEM
theme:
  name: sandstone
  navigation_depth: 4
  nav_style: light

nav:
  - Home: index.md
  - Examples:
    - Random packing: examples/random_packing.md
    - Triaxial compression: examples/triaxial_compression.md
    - Direct shear: examples/direct_shear.md
    - Angle of repose: examples/angle_of_repose.md
    - Works based on NetDEM: examples/works_based_on_netdem.md
    - Gallery: examples/gallery.md
  - Documentation: 
    - Installation: documentation/installation.md
    - Usage: documentation/usage.md  
    - Developer manual: documentation/developer_manual.md
    - Code manual: documentation/code_manual.md
    - DEM manual: documentation/dem_manual.md
  - Code Doxygen: doxygen/html/index.html
  - About:
    - Bugs & feature request: about/bugs_&_feature_requests.md
    - Copyright: about/copyright_and_license.md
    - Acknowledgement: about/acknowledgement.md  
    - Developer team: about/developer_team.md

markdown_extensions: 
  - pymdownx.arithmatex
  - attr_list
  - extra
  - fenced_code  
  - footnotes

extra:
  include_next_prev: false  

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML